
class EnvConfig:
    NUM_VEHICLES = 20
    NUM_BASESTATIONS = 6
    NUM_EDGE_SERVERS = 5
    STEP = 50
    TASK_GENERATION_PRO = 0.50
    EPISODES = 400
    IS_BASE = False
    # RANDOM_SEED = 100
    RANDOM_SEED = 42
    IS_SMOOTH_DATA = True